- name: Preparacion de los nodos workers
  hosts: kubernetes_workers
  become: yes
  tasks:
    - name: Generar el comando kubeadm join desde un nodo master
      command: kubeadm token create --print-join-command
      register: kubeadm_join_command
      delegate_to: "{{ groups['kubernetes_masters'][0] }}"
      run_once: true
      become: true
      changed_when: false

    - name: Guardar el comando de unión en el host master
      set_fact:
        kubeadm_join_command: "{{ kubeadm_join_command.stdout | trim }}"
      delegate_to: "{{ groups['kubernetes_masters'][0] }}"
      run_once: true

    - name: Unir el nodo worker al cluster
      command: "{{ hostvars[groups['kubernetes_masters'][0]].kubeadm_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf


