---
- name: Crear StorageClass
  hosts: master01

  tasks:

    - name: Crear StorageClass
      kubernetes.core.k8s:
        state: present

        definition:

          apiVersion: storage.k8s.io/v1
          kind: StorageClass

          metadata:
            name: nfs-client

          provisioner: cluster.local/nfs-subdir-external-provisioner

          reclaimPolicy: Delete

          volumeBindingMode: Immediate

          allowVolumeExpansion: true

    - name: Mostrar StorageClass
      ansible.builtin.command:
        cmd: kubectl get storageclass
      register: salida

    - debug:
        var: salida.stdout_lines