---
- name: Limpiar TinyProxy
  hosts: "{{ target_hosts | default('tinyproxy') }}"
  become: yes
  tasks:
    - name: Eliminar las variables de entorno en tu terminal actual
      shell: |
        unset http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY
      args:
        executable: /bin/bash

    - name: Eliminar la configuración del proxy para APT
      file:
        path: /etc/apt/apt.conf.d/99proxy
        state: absent

    - name: Eliminar la configuración del proxy para containerd
      file:
        path: /etc/systemd/system/containerd.service.d/proxy.conf
        state: absent
