---
# roles/11k8s_masters/defaults/main.yml
kubeconfig_path: /etc/kubernetes/admin.conf
pod_network_cidr: 192.168.0.0/16

# Versión exacta para el pre-pull
k8s_version_pull: "v1.33.1"
cilium_version: "1.17.4"

# Endpoint dinámico apuntando al HAProxy (Grupo lb, primer host)
control_plane_endpoint: "{{ groups['lb'][0] }}:6443"

# Variables de Proxy que hereda de la configuración local
proxy_host: "{{ hostvars['localhost'].tinyproxy_host | default(hostvars['localhost']['ansible_default_ipv4']['address']) }}"
proxy_port: "{{ hostvars['localhost'].tinyproxy_port }}"
k8s_no_proxy: "localhost,127.0.0.1,10.12.0.0/16,*.uclv.cu,*.uclv.edu.cu,repos.uclv.edu.cu"